### ISSUE TITLE
template extensions in /templates/build (and bench)

### ISSUE THREAD

**Issue by milfeld** [TACC/benchpro#2]
When modifying templates, I would like to keep a backup of the original file in the same directory.  Could you possibly add the feature (if not already present) to ignore files not ending with the ".template" suffix in the `templates/build` and `templates/bench` directories?  (E.g. I would like to backup `gromacs.template` as `gromacs.template.0`, or gromacs.template.bac, or gromacs.template.orig, etc.)

Best,
Kent

**Comment by mrcawood** [comment]
this is indeed already implemented for both .cfg and .template files.
