### ISSUE TITLE
providing more help information for OVERLOAD

### ISSUE THREAD

**Issue by milfeld** [TACC/benchpro#4]
bp -h Provides this information

...
```
 -o OVERLOAD [OVERLOAD ...], --overload OVERLOAD [OVERLOAD ...]
                        Override any setting read from cfg files. Accepts
                        space delimited list of assignments.
```

However OVERLOADs can be key-value pairs in **ini**files, too, and it might be good to give the syntax of an OVERLOAD "assignment", something like this:
```
 -o OVERLOAD [OVERLOAD ...], --overload OVERLOAD [OVERLOAD ...]
                        Override any settings read from cfg or ini files. 
                        OVERLOAD is a key-value pair of the form key=value.
```
Or you can simply state "OVERLOAD is a key-value pair assignment".  
It is not necessary to state "Accepts space delimited list" because OVERLOAD [OVERLOAD ...] shows that.

**Comment by mrcawood** [comment]
thanks, updated
